name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: read

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze openai
      - name: Build executable
        run: python setup.py build
      - name: Zip artifacts
        run: Compress-Archive -Path build/exe.* -DestinationPath deepseek-windows.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: deepseek-windows.zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze openai
      - name: Build executable
        run: python setup.py build
      - name: Zip artifacts
        run: zip -r deepseek-macos.zip build/exe.*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: deepseek-macos.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cx_Freeze openai
      - name: Build executable
        run: python setup.py build
      - name: Zip artifacts
        run: zip -r deepseek-linux.zip build/exe.*
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: deepseek-linux.zip

  create-release:
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-build/deepseek-windows.zip
            macos-build/deepseek-macos.zip
            linux-build/deepseek-linux.zip
          draft: false
          prerelease: false